#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - curl
  - unzip
  - software-properties-common
  - ca-certificates
  - gnupg
  - lsb-release
  - adduser
  - libfontconfig1

